from rest_framework import serializers

from .models import Item


# Converts Item objects to JSON and validates JSON sent by browser.
class ItemSerializer(serializers.ModelSerializer):
    class Meta:
        # Use the Item model and expose only these fields in API responses.
        model = Item
        fields = ["id", "name", "group", "created_at", "updated_at"]

        # IDs and timestamps are generated by Django, not mutable by users.
        read_only_fields = ["id", "created_at", "updated_at"]

        # Use validate() below for consistent duplicate name error message.
        validators = []

    def validate_name(self, value):
        # Remove whitespace before a name is saved.
        # Do not allow empty names.
        value = value.strip()
        if not value:
            raise serializers.ValidationError("Name cannot be empty.")
        return value

    def validate(self, attrs):
        # PATCH might only contain one field. For omitted fields, use
        # the current Item values so we check the complete name/group pair.
        name = attrs.get("name", self.instance.name if self.instance else None)
        group = attrs.get("group", self.instance.group if self.instance else None)

        if name and group:
            # A name may appear in another group, but not twice in one group.
            # iexact treats names capitilized differently as duplicates (case insensitive).
            matches = Item.objects.filter(name__iexact=name, group=group)
            if self.instance:
                # The Item being edited is not a duplicate of itself, so exclude it.
                matches = matches.exclude(pk=self.instance.pk)
            if matches.exists():
                raise serializers.ValidationError(
                    "An item with this name already exists in this group."
                )

        # Return the validated fields to DRF for create or update.
        return attrs
